name: Update README

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Append 'a' to README
        run: |
          echo "a" >> README.md
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -am "Add 'a' to README"
          git push
